- name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Dockerhub'dan en güncel imajı çek
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/banking-app:latest
            
            # Eğer varsa eski konteyneri temizle ve yeni imajla başlat
            # sudo ekleyerek yetki sorunlarını, full path ile komut sorunlarını çözüyoruz
            sudo docker stop banking-container || true
            sudo docker rm banking-container || true
            sudo docker run -d --name banking-container -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/banking-app:latest
